name: Publish
on:
  push:
    tags:
      - '*'
  workflow_dispatch:

env:
  GRADLE_OPTS: "-Dorg.gradle.jvmargs=-Xmx4g -Dorg.gradle.daemon=false -Dkotlin.incremental=false"

jobs:
  publish-maven:
    name: Publish to Maven
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Configure JDK
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 11

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: wrapper

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Publish to Repository
        run: ./gradlew :ychat:clean publishReleasePublicationToYChatRepository

        env:
          MAVEN_USERNAME: ${{ secrets.MAVEN_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.MAVEN_PASSWORD}}
          MEMORY_KEY: ${{ secrets.MEMORY_KEY}}
          SIGNINGKEY: ${{ secrets.SIGNINGKEY}}
          SIGNINGPASSWORD: ${{ secrets.SIGNINGPASSWORD}}
