name: Publish
on:
  push:
    tags:
      - '*'
jobs:
  publish-maven:
    name: Publish to Maven
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Java for publishing to Maven Central Repository
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Publish to Repository
        run: ./gradlew :chat-gpt:clean publishReleasePublicationToYChatGPTRepository

        env:
          MAVEN_USERNAME: ${{ secrets.MAVENCENTRALUSERNAME }}
          MAVEN_PASSWORD: ${{ secrets.MAVENCENTRALPASSWORD}}
          MEMORY_KEY: ${{ secrets.SIGNINGINMEMORYKEY}}
          SIGNINGKEY: ${{ secrets.SIGNINGKEYID}}
          SIGNINGPASSWORD: ${{ secrets.SIGNINGPASSWORD}}
